/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package state_student_management.Transport;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.Train;
import Business.Organization.TrainDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TransportRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import state_student_management.University.University;

/**
 *
 * @author bhaveshraja
 */
public class TrainManagerDashboard extends javax.swing.JPanel {

    /**
     * Creates new form TrainManagerDashboard
     */
    EcoSystem ecosystem;
    Organization organization;
    UserAccount userAccount;
    JPanel userProcessContainer;
    Train train;
    TrainDirectory trainDirectory;
    private Enterprise enterprise;
    private OrganizationDirectory organizationDirectory;
    ArrayList<Train> trainList = new ArrayList<>();
    DefaultTableModel trn,loco,trainReq;
    int row, col;
    private DB4OUtil dB4OUtil; 
    
    public TrainManagerDashboard(JPanel userProcessContainer, EcoSystem ecosystem, Organization organization, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.organization = organization;
        this.userAccount = userAccount;
     
        trn = (DefaultTableModel) tblTrains.getModel();
        loco = (DefaultTableModel) tblLocoEngineers.getModel();
        trainReq = (DefaultTableModel) tblTransportRequests1.getModel();
        
        dB4OUtil = DB4OUtil.getInstance();
        
        populateTrainTable();
        populateTrainRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        txtRole = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ProfessorDirectoryPane = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTrains = new javax.swing.JTable();
        btnDeleteTrain = new javax.swing.JButton();
        btnViewTrain = new javax.swing.JButton();
        btnAddTrain = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTrainNumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRouteNumberTrain = new javax.swing.JTextField();
        btnUpdateTrain = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLocoEngineers = new javax.swing.JTable();
        btnDeleteLocoEngineer = new javax.swing.JButton();
        btnUpdateLocoEngineer = new javax.swing.JButton();
        btnAddEngineer = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtLocoEngineerName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtLocoEngineerEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLocoEngineerGender = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtLocoEngineerAge = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtLocoEngineerSSN = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboTransportType = new javax.swing.JComboBox<>();
        btnViewLocoEngineer = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblTransportRequests1 = new javax.swing.JTable();
        btnReject = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(201, 3, 3));

        jLabel1.setText("jLabel1");

        btnLogout.setForeground(new java.awt.Color(138, 138, 138));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Role");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ProfessorDirectoryPane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel8.setText("Trains");

        tblTrains.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Train Number", "Route Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTrains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrainsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTrains);

        btnDeleteTrain.setBackground(new java.awt.Color(245, 1, 1));
        btnDeleteTrain.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteTrain.setText("Delete");
        btnDeleteTrain.setBorder(null);
        btnDeleteTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTrainActionPerformed(evt);
            }
        });

        btnViewTrain.setBackground(new java.awt.Color(52, 51, 242));
        btnViewTrain.setForeground(new java.awt.Color(255, 255, 255));
        btnViewTrain.setText("View");
        btnViewTrain.setBorder(null);
        btnViewTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTrainActionPerformed(evt);
            }
        });

        btnAddTrain.setBackground(new java.awt.Color(201, 3, 3));
        btnAddTrain.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTrain.setText("Add Train");
        btnAddTrain.setBorder(null);
        btnAddTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTrainActionPerformed(evt);
            }
        });

        jLabel10.setText("Train Number");

        jLabel12.setText("Route Name");

        btnUpdateTrain.setBackground(new java.awt.Color(52, 51, 242));
        btnUpdateTrain.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateTrain.setText("Update");
        btnUpdateTrain.setBorder(null);
        btnUpdateTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTrainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnUpdateTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnDeleteTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtTrainNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtRouteNumberTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(btnAddTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnViewTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrainNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRouteNumberTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addComponent(btnAddTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        ProfessorDirectoryPane.addTab("Trains", jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel9.setText("Loco Engineers");

        tblLocoEngineers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Gender", "Age", "SSN", "Transport Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLocoEngineers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLocoEngineersMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblLocoEngineers);

        btnDeleteLocoEngineer.setBackground(new java.awt.Color(245, 1, 1));
        btnDeleteLocoEngineer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteLocoEngineer.setText("Delete");
        btnDeleteLocoEngineer.setBorder(null);
        btnDeleteLocoEngineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLocoEngineerActionPerformed(evt);
            }
        });

        btnUpdateLocoEngineer.setBackground(new java.awt.Color(52, 51, 242));
        btnUpdateLocoEngineer.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateLocoEngineer.setText("Update");
        btnUpdateLocoEngineer.setBorder(null);
        btnUpdateLocoEngineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLocoEngineerActionPerformed(evt);
            }
        });

        btnAddEngineer.setBackground(new java.awt.Color(201, 3, 3));
        btnAddEngineer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEngineer.setText("Add Engineer");
        btnAddEngineer.setBorder(null);
        btnAddEngineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEngineerActionPerformed(evt);
            }
        });

        jLabel13.setText("Name");

        jLabel14.setText("Email");

        jLabel17.setText("Gender");

        txtLocoEngineerGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocoEngineerGenderActionPerformed(evt);
            }
        });

        jLabel18.setText("Age");

        txtLocoEngineerAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocoEngineerAgeActionPerformed(evt);
            }
        });

        jLabel19.setText("SSN");

        txtLocoEngineerSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocoEngineerSSNActionPerformed(evt);
            }
        });

        jLabel20.setText("Transport Type");

        jComboTransportType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTransportTypeActionPerformed(evt);
            }
        });

        btnViewLocoEngineer.setBackground(new java.awt.Color(52, 51, 242));
        btnViewLocoEngineer.setForeground(new java.awt.Color(255, 255, 255));
        btnViewLocoEngineer.setText("View");
        btnViewLocoEngineer.setBorder(null);
        btnViewLocoEngineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLocoEngineerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewLocoEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateLocoEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteLocoEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel17)
                                            .addComponent(txtLocoEngineerName)
                                            .addComponent(txtLocoEngineerGender, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtLocoEngineerAge, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14)
                                                .addComponent(txtLocoEngineerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(118, 118, 118))))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(txtLocoEngineerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jComboTransportType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(btnAddEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteLocoEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateLocoEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewLocoEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLocoEngineerName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocoEngineerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(0, 0, 0)
                                .addComponent(txtLocoEngineerGender, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(0, 0, 0)
                                .addComponent(txtLocoEngineerAge, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, 0)
                                .addComponent(txtLocoEngineerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, 0)
                                .addComponent(jComboTransportType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        ProfessorDirectoryPane.addTab("Loco Engineers", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel11.setText("Transport Requests");

        tblTransportRequests1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Univeristy Name", "No.of Students", "Route Name", "Type of Transport", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTransportRequests1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransportRequests1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblTransportRequests1);

        btnReject.setBackground(new java.awt.Color(255, 51, 51));
        btnReject.setForeground(new java.awt.Color(255, 255, 255));
        btnReject.setText("Reject");
        btnReject.setBorder(null);
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnAccept.setBackground(new java.awt.Color(0, 153, 0));
        btnAccept.setForeground(new java.awt.Color(255, 255, 255));
        btnAccept.setText("Accept");
        btnAccept.setBorder(null);
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        ProfessorDirectoryPane.addTab("Transport Requests", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProfessorDirectoryPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfessorDirectoryPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewTrainActionPerformed

    private void btnUpdateLocoEngineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLocoEngineerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateLocoEngineerActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        row = tblTransportRequests1.getSelectedRow();
        String currentStatus = trainReq.getValueAt(row, 3).toString();
        if(currentStatus.equalsIgnoreCase("Request raised"))
        {
            organization.getWorkQueue().getListOfWorkQueues().get(row).setStatus("Request Rejected");
            JOptionPane.showMessageDialog(this, "Request is Rejected", " Request Rejected", 1);
    
        }
         else if(currentStatus.equalsIgnoreCase("Request Declined")){
            
            JOptionPane.showMessageDialog(this, "This request is Already declined earlier", " Request declined", 1);
            
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Request is already accepted", " Request Accepted", 1);
            
        }
        populateTrainRequestTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnUpdateTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateTrainActionPerformed

    private void txtLocoEngineerGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocoEngineerGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocoEngineerGenderActionPerformed

    private void txtLocoEngineerAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocoEngineerAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocoEngineerAgeActionPerformed

    private void txtLocoEngineerSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocoEngineerSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocoEngineerSSNActionPerformed

    private void jComboTransportTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTransportTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTransportTypeActionPerformed

    private void btnViewLocoEngineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLocoEngineerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewLocoEngineerActionPerformed

    private void btnAddTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTrainActionPerformed
        // TODO add your handling code here:
        int trainNumber = Integer.parseInt(txtTrainNumber.getText().trim());
        String routeNameT = txtRouteNumberTrain.getText().trim();
        
        Train train = new Train(trainNumber,routeNameT );
        
        organization.trainDirectory.addTrain(train);
        populateTrainTable();
        
        
        //Object[] data = {trainNumber, routeNameT};
        //trn.addRow(data);
        
        txtTrainNumber.setText("");
        txtRouteNumberTrain.setText("");
        
        
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_btnAddTrainActionPerformed

    private void tblTrainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrainsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblTrains.getModel();
        
        String trainNumber = model.getValueAt(tblTrains.getSelectedRow(), 0).toString();
        String routeNameT = model.getValueAt(tblTrains.getSelectedRow(), 1).toString();
        
        txtTrainNumber.setText(trainNumber);
        txtRouteNumberTrain.setText(routeNameT);
        
    }//GEN-LAST:event_tblTrainsMouseClicked

    private void btnDeleteTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTrainActionPerformed
        // TODO add your handling code here:
        trn.removeRow(row);
        
        txtTrainNumber.setText("");
        txtRouteNumberTrain.setText("");
        
    }//GEN-LAST:event_btnDeleteTrainActionPerformed

    private void btnAddEngineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEngineerActionPerformed
        // TODO add your handling code here:
        String locoName = txtLocoEngineerName.getText().trim();
        String locoEmail = txtLocoEngineerEmail.getText().trim();
        String locoGender = txtLocoEngineerGender.getText().trim();
        int locoAge = Integer.parseInt(txtLocoEngineerAge.getText().trim());
        int locoSSN = Integer.parseInt(txtLocoEngineerSSN.getText().trim());
                
        Object[] data = {locoName, locoEmail, locoGender, locoAge, locoSSN};
        loco.addRow(data);
        
        txtLocoEngineerName.setText("");
        txtLocoEngineerEmail.setText("");
        txtLocoEngineerGender.setText("");
        txtLocoEngineerAge.setText("");
        txtLocoEngineerSSN.setText("");
                
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_btnAddEngineerActionPerformed

    private void tblLocoEngineersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLocoEngineersMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblLocoEngineers.getModel();
        
        String locoName = model.getValueAt(tblLocoEngineers.getSelectedRow(), 0).toString();
        String locoEmail = model.getValueAt(tblLocoEngineers.getSelectedRow(), 1).toString();
        String locoGender = model.getValueAt(tblLocoEngineers.getSelectedRow(), 2).toString();
        String locoAge = model.getValueAt(tblLocoEngineers.getSelectedRow(), 3).toString();
        String locoSSN = model.getValueAt(tblLocoEngineers.getSelectedRow(), 4).toString();

        
        txtLocoEngineerName.setText(locoName);
        txtLocoEngineerEmail.setText(locoEmail);
        txtLocoEngineerGender.setText(locoGender);
        txtLocoEngineerAge.setText(locoAge);
        txtLocoEngineerSSN.setText(locoSSN);

        
    }//GEN-LAST:event_tblLocoEngineersMouseClicked

    private void btnDeleteLocoEngineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLocoEngineerActionPerformed
        // TODO add your handling code here:
        loco.removeRow(row);
        
        txtLocoEngineerName.setText("");
        txtLocoEngineerEmail.setText("");
        txtLocoEngineerGender.setText("");
        txtLocoEngineerAge.setText("");
        txtLocoEngineerSSN.setText("");
    }//GEN-LAST:event_btnDeleteLocoEngineerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.next(userProcessContainer);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        
         String currentStatus = trainReq.getValueAt(row, 3).toString();
        
        if(currentStatus.equalsIgnoreCase("Request raised"))
        {
            organization.getWorkQueue().getListOfWorkQueues().get(row).setStatus("Request Accepted");          
            JOptionPane.showMessageDialog(this, "Request is Accepted", " Request Accepted", 1);
           
        }
        
        else if(currentStatus.equalsIgnoreCase("Request Declined")){
            
            JOptionPane.showMessageDialog(this, "This request is Already declined earlier", " Request declined", 1);
            
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Request is already accepted", " Request Accepted", 1);
            
        }
        
        populateTrainRequestTable();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void tblTransportRequests1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransportRequests1MouseClicked
        // TODO add your handling code here:
        
        row = tblTransportRequests1.getSelectedRow();
        col = tblTransportRequests1.getSelectedColumn();
    }//GEN-LAST:event_tblTransportRequests1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ProfessorDirectoryPane;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAddEngineer;
    private javax.swing.JButton btnAddTrain;
    private javax.swing.JButton btnDeleteLocoEngineer;
    private javax.swing.JButton btnDeleteTrain;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnUpdateLocoEngineer;
    private javax.swing.JButton btnUpdateTrain;
    private javax.swing.JButton btnViewLocoEngineer;
    private javax.swing.JButton btnViewTrain;
    private javax.swing.JComboBox<String> jComboTransportType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblLocoEngineers;
    private javax.swing.JTable tblTrains;
    private javax.swing.JTable tblTransportRequests1;
    private javax.swing.JTextField txtLocoEngineerAge;
    private javax.swing.JTextField txtLocoEngineerEmail;
    private javax.swing.JTextField txtLocoEngineerGender;
    private javax.swing.JTextField txtLocoEngineerName;
    private javax.swing.JTextField txtLocoEngineerSSN;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtRouteNumberTrain;
    private javax.swing.JTextField txtTrainNumber;
    // End of variables declaration//GEN-END:variables

private void populateTrainTable() {
       
        trn.setRowCount(0);
      
        for (Train train : this.organization.getTrainDirectory().getTrainList()) {
            
               Object[] objs = {train.getTrainNumber(), train.getRouteName()};                       
               trn.addRow(objs);
           }
        }


 private void populateTrainRequestTable() {
      trainReq.setRowCount(0);
        
        WorkQueue workQueue = organization.getWorkQueue();
        
        for(WorkRequest workRequest  : workQueue.getListOfWorkQueues() ){
            TransportRequest req = (TransportRequest) workRequest;
              
            
            Date date = null;
            if(req.getStatus().equalsIgnoreCase("Request Accepted")) {
                  date = req.getResolveDate();
            }

            Object[] objs = {req.getSender().getStudent().getName(),req.getPriority(), req.getMessage(), req.getStatus(),req.getRequestDate(),date};
            trainReq.addRow(objs);
            
        }
    }

}
