/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package state_student_management.University;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhaveshraja
 */
public class CollegeAdminDashboard extends javax.swing.JPanel {

    /**
     * Creates new form CollegeAdminDashboard1
     */
    EcoSystem ecosystem;
    University university;
    UserAccount userAccount;
    JPanel userProcessContainer;
    ArrayList<University> universityList = new ArrayList<>();
    DefaultTableModel cl1,crse1,sdnt1,prof1;
    int row, col;
    private DB4OUtil dB4OUtil; 
    
    public CollegeAdminDashboard(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount account) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        this.university = university;
        //cl1 = (DefaultTableModel) tblColleges.getModel();
        crse1 = (DefaultTableModel) tblCourses1.getModel();
        sdnt1 = (DefaultTableModel) tblStudents1.getModel();
        prof1 = (DefaultTableModel) tblProfessors1.getModel();


        dB4OUtil = DB4OUtil.getInstance();
        //populateUniversityTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        txtRole = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ProfessorDirectoryPane = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCourses1 = new javax.swing.JTable();
        btnDeleteCourse = new javax.swing.JButton();
        btnViewCourse = new javax.swing.JButton();
        btnAddCourse = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCreditHours = new javax.swing.JTextField();
        btnUpdateCourse = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblStudents1 = new javax.swing.JTable();
        btnDeleteStudent = new javax.swing.JButton();
        btnUpdateCollege = new javax.swing.JButton();
        btnAddStudent = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtNameStudentClg = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtEmailStudentClg = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtGenderStudentClg = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtAgeStudentClg = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtAddressStudentClg = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jComboUniversitiesStudentClg = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jComboCollegesStudentClg = new javax.swing.JComboBox<>();
        btnViewStudent = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblProfessors1 = new javax.swing.JTable();
        btnDeleteProfessors = new javax.swing.JButton();
        btnUpdateColleges = new javax.swing.JButton();
        btnViewCollegess = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(201, 3, 3));

        jLabel1.setText("jLabel1");

        btnLogout.setForeground(new java.awt.Color(138, 138, 138));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Role");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        ProfessorDirectoryPane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel8.setText("Courses Directory");

        tblCourses1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Credit Hours", "Professor", "University", "College", "Price", "Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourses1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourses1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCourses1);

        btnDeleteCourse.setBackground(new java.awt.Color(245, 1, 1));
        btnDeleteCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCourse.setText("Delete");
        btnDeleteCourse.setBorder(null);
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        btnViewCourse.setBackground(new java.awt.Color(52, 51, 242));
        btnViewCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCourse.setText("View");
        btnViewCourse.setBorder(null);
        btnViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseActionPerformed(evt);
            }
        });

        btnAddCourse.setBackground(new java.awt.Color(201, 3, 3));
        btnAddCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCourse.setText("Add Course");
        btnAddCourse.setBorder(null);
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        jLabel22.setText("Name");

        jLabel21.setText("Seats");

        jLabel24.setText("Credit Hours");

        txtCreditHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditHoursActionPerformed(evt);
            }
        });

        btnUpdateCourse.setBackground(new java.awt.Color(52, 51, 242));
        btnUpdateCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCourse.setText("Update");
        btnUpdateCourse.setBorder(null);
        btnUpdateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel24)
                                    .addComponent(txtCreditHours, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCreditHours, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        ProfessorDirectoryPane.addTab("Courses", jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel9.setText("Students");

        tblStudents1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Gender", "Age", "Address", "University", "College"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudents1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudents1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblStudents1);

        btnDeleteStudent.setBackground(new java.awt.Color(245, 1, 1));
        btnDeleteStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteStudent.setText("Delete");
        btnDeleteStudent.setBorder(null);
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        btnUpdateCollege.setBackground(new java.awt.Color(52, 51, 242));
        btnUpdateCollege.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCollege.setText("Update");
        btnUpdateCollege.setBorder(null);
        btnUpdateCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCollegeActionPerformed(evt);
            }
        });

        btnAddStudent.setBackground(new java.awt.Color(201, 3, 3));
        btnAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudent.setText("Add Student");
        btnAddStudent.setBorder(null);
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        jLabel33.setText("Name");

        txtNameStudentClg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameStudentClgActionPerformed(evt);
            }
        });

        jLabel34.setText("Email");

        txtEmailStudentClg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailStudentClgActionPerformed(evt);
            }
        });

        jLabel35.setText("Gender");

        txtGenderStudentClg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderStudentClgActionPerformed(evt);
            }
        });

        jLabel36.setText("Age");

        txtAgeStudentClg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeStudentClgActionPerformed(evt);
            }
        });

        jLabel37.setText("Address");

        txtAddressStudentClg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressStudentClgActionPerformed(evt);
            }
        });

        jLabel38.setText("University");

        jLabel39.setText("College");

        btnViewStudent.setBackground(new java.awt.Color(52, 51, 242));
        btnViewStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnViewStudent.setText("View");
        btnViewStudent.setBorder(null);
        btnViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel33)
                                .addGap(135, 135, 135))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(txtNameStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel34))
                            .addComponent(txtEmailStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel35))
                            .addComponent(txtGenderStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel36))
                            .addComponent(txtAgeStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(jComboUniversitiesStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel37))
                            .addComponent(txtAddressStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(jComboCollegesStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(69, 69, 69)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGenderStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgeStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddressStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboUniversitiesStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboCollegesStudentClg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProfessorDirectoryPane.addTab("Students", jPanel7);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tblProfessors1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Mobile", "Specialization", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProfessors1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProfessors1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblProfessors1);

        btnDeleteProfessors.setBackground(new java.awt.Color(245, 1, 1));
        btnDeleteProfessors.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteProfessors.setText("Delete");
        btnDeleteProfessors.setBorder(null);
        btnDeleteProfessors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProfessorsActionPerformed(evt);
            }
        });

        btnUpdateColleges.setBackground(new java.awt.Color(52, 51, 242));
        btnUpdateColleges.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateColleges.setText("Update");
        btnUpdateColleges.setBorder(null);
        btnUpdateColleges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCollegesActionPerformed(evt);
            }
        });

        btnViewCollegess.setBackground(new java.awt.Color(52, 51, 242));
        btnViewCollegess.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCollegess.setText("View");
        btnViewCollegess.setBorder(null);
        btnViewCollegess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCollegessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnViewCollegess, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateColleges, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDeleteProfessors, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateColleges, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCollegess, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteProfessors, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        ProfessorDirectoryPane.addTab("Professors", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProfessorDirectoryPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfessorDirectoryPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCourseActionPerformed

    private void btnUpdateCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCollegeActionPerformed

    private void btnUpdateCollegesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCollegesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCollegesActionPerformed

    private void txtCreditHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditHoursActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        // TODO add your handling code here:
        crse1.removeRow(row);
        
        txtCourse.setText("");
        txtSeats.setText("");
        txtCreditHours.setText("");
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnUpdateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCourseActionPerformed

    private void txtNameStudentClgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameStudentClgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameStudentClgActionPerformed

    private void txtEmailStudentClgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailStudentClgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailStudentClgActionPerformed

    private void txtGenderStudentClgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderStudentClgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderStudentClgActionPerformed

    private void txtAgeStudentClgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeStudentClgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeStudentClgActionPerformed

    private void txtAddressStudentClgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressStudentClgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressStudentClgActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        // TODO add your handling code here:
        sdnt1.removeRow(row);
        
        txtNameStudentClg.setText("");
        txtEmailStudentClg.setText("");
        txtGenderStudentClg.setText("");
        txtAgeStudentClg.setText("");
        txtAddressStudentClg.setText("");
        
        
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewStudentActionPerformed

    private void btnViewCollegessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCollegessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCollegessActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
       String nameCourse1 = txtCourse.getText().trim();
       int seatsCourse1 = Integer.parseInt(txtSeats.getText().trim());
       int creditHours1 = Integer.parseInt(txtCreditHours.getText().trim());
       //int price1 = Integer.parseInt(txtPrice.getText().trim());
        
        //University universityList=new University(name,offemail, offtel, established, address);
        //cityList.add(city);
        Object[] data = {nameCourse1, seatsCourse1, creditHours1};
        crse1.addRow(data);
        
//        if (!name.isEmpty()) {
//            if (ecosystem.isUnique(name)) {
//                University university = ecosystem.createAndAddUniversity();
//                university.setName(name);
//                university.setOffemail(offemail);
//                university.setOfftel(offtel);
//                university.setEstablished(established);
//                university.setAddress(address);
//              
//                JOptionPane.showMessageDialog(null, "University Successfully Created");
//                
//            {
//               JOptionPane.showMessageDialog(null, "University Already Exits");
//            }
//        }
//        else {
//            JOptionPane.showMessageDialog(null, "Enter university name");
//        }
//        
        //populateUniversityTable();
        txtCourse.setText("");
        txtSeats.setText("");
        txtCreditHours.setText("");
//        txtPrice.setText("");
        
        dB4OUtil.storeSystem(ecosystem);
                                                   
    //}  
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void tblCourses1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourses1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblCourses1.getModel();

        String nameCourse1 = model.getValueAt(tblCourses1.getSelectedRow(), 0).toString();
        String seatsCourse1 = model.getValueAt(tblCourses1.getSelectedRow(), 1).toString();
        String creditHours1 = model.getValueAt(tblCourses1.getSelectedRow(), 2).toString();
        String price1 = model.getValueAt(tblCourses1.getSelectedRow(), 3).toString();
        

        txtCourse.setText(nameCourse1);
        txtSeats.setText(seatsCourse1);
        txtCreditHours.setText(creditHours1);
        //txtPrice.setText(price1);
        
    }//GEN-LAST:event_tblCourses1MouseClicked

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        // TODO add your handling code here:
        String studentName1 = txtNameStudentClg.getText().trim();
       String studentEmail1 = txtEmailStudentClg.getText().trim();
       String studentGender1 = txtGenderStudentClg.getText().trim();
       int studentAge1 = Integer.parseInt(txtAgeStudentClg.getText().trim());
       String studentAddress1 = txtAddressStudentClg.getText().trim();
        
        //University universityList=new University(name,offemail, offtel, established, address);
        //cityList.add(city);
        Object[] data = {studentName1, studentEmail1, studentGender1, studentAge1, studentAddress1 };
        sdnt1.addRow(data);
        
//        if (!name.isEmpty()) {
//            if (ecosystem.isUnique(name)) {
//                University university = ecosystem.createAndAddUniversity();
//                university.setName(name);
//                university.setOffemail(offemail);
//                university.setOfftel(offtel);
//                university.setEstablished(established);
//                university.setAddress(address);
//              
//                JOptionPane.showMessageDialog(null, "University Successfully Created");
//                
//            {
//               JOptionPane.showMessageDialog(null, "University Already Exits");
//            }
//        }
//        else {
//            JOptionPane.showMessageDialog(null, "Enter university name");
//        }
//        
        //populateUniversityTable();
        txtNameStudentClg.setText("");
        txtEmailStudentClg.setText("");
        txtGenderStudentClg.setText("");
        txtAgeStudentClg.setText("");
        txtAddressStudentClg.setText("");

        dB4OUtil.storeSystem(ecosystem);
                                                   
    //} 
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void tblStudents1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudents1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblStudents1.getModel();

        String studentName1 = model.getValueAt(tblStudents1.getSelectedRow(), 0).toString();
        String studentEmail1 = model.getValueAt(tblStudents1.getSelectedRow(), 1).toString();
        String studentGender1 = model.getValueAt(tblStudents1.getSelectedRow(), 2).toString();
        String studentAge1 = model.getValueAt(tblStudents1.getSelectedRow(), 3).toString();
        String studentAddress1 = model.getValueAt(tblStudents1.getSelectedRow(), 4).toString();

        

        txtNameStudentClg.setText(studentName1);
        txtEmailStudentClg.setText(studentEmail1);
        txtGenderStudentClg.setText(studentGender1);
        txtAgeStudentClg.setText(studentAge1);
        txtAddressStudentClg.setText(studentAddress1);  
    }//GEN-LAST:event_tblStudents1MouseClicked

    private void tblProfessors1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProfessors1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tblProfessors1.getModel();

        String professorName1 = model.getValueAt(tblProfessors1.getSelectedRow(), 0).toString();
        String professorEmail1 = model.getValueAt(tblProfessors1.getSelectedRow(), 1).toString();
        String professorTelephone1 = model.getValueAt(tblProfessors1.getSelectedRow(), 2).toString();
        String professorSalary1 = model.getValueAt(tblProfessors1.getSelectedRow(), 3).toString();
        String professorPassword1 = model.getValueAt(tblProfessors1.getSelectedRow(), 4).toString();

//        txtProfessorsName.setText(professorName1);
//        txtProfessorsEmail.setText(professorEmail1);
//        txtProfessorsTelephone.setText(professorTelephone1);
//        txtProfessorUsername.setText(professorSalary1);
//        jPasswordFieldProfessors.setText(professorPassword1);
        
    }//GEN-LAST:event_tblProfessors1MouseClicked

    private void btnDeleteProfessorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProfessorsActionPerformed
        // TODO add your handling code here:
        prof1.removeRow(row);
        
//        txtProfessorsName.setText("");
//        txtProfessorsEmail.setText("");
//        txtProfessorsTelephone.setText("");
//        txtProfessorUsername.setText("");
//        jPasswordFieldProfessors.setText("");
        
    }//GEN-LAST:event_btnDeleteProfessorsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.next(userProcessContainer);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ProfessorDirectoryPane;
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnDeleteProfessors;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateCollege;
    private javax.swing.JButton btnUpdateColleges;
    private javax.swing.JButton btnUpdateCourse;
    private javax.swing.JButton btnViewCollegess;
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JButton btnViewStudent;
    private javax.swing.JComboBox<String> jComboCollegesStudentClg;
    private javax.swing.JComboBox<String> jComboUniversitiesStudentClg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblCourses1;
    private javax.swing.JTable tblProfessors1;
    private javax.swing.JTable tblStudents1;
    private javax.swing.JTextField txtAddressStudentClg;
    private javax.swing.JTextField txtAgeStudentClg;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtCreditHours;
    private javax.swing.JTextField txtEmailStudentClg;
    private javax.swing.JTextField txtGenderStudentClg;
    private javax.swing.JTextField txtNameStudentClg;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtSeats;
    // End of variables declaration//GEN-END:variables
}
